apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress-laith
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.erfan-us.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-stack-grafana
                port:
                  number: 80