apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: erfan-resume
  name: erfan-resume
  namespace: web
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erfan-resume
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-29T03:42:12-05:00"
      labels:
        app: erfan-resume
    spec:
      containers:
        - image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: html-content
              readOnly: true
              subPath: index.html
            - mountPath: /usr/share/nginx/html/erfan-resume.docx
              name: docx-content
              readOnly: true
              subPath: erfan-resume.docx
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: erfan-resume-content
          name: html-content
        - name: docx-content
          secret:
            defaultMode: 420
            secretName: erfan-resume-file
